"use client";

/**
 * UnderstandingCheck — asks WHY before letting the student move on.
 * ─────────────────────────────────────────────────────────────────────
 * Owner: Person 1, question generated by Person 2's reasoning call.
 *
 * The question is never from a hardcoded bank. It is a field on the
 * reasoning state, generated from this student's actual event history,
 * which is why it can reference what they just did.
 *
 * Grading happens here for UI speed, but the result is written as an event
 * and every metric reads from there — the strip is not counting this
 * component's local state.
 */

import { useState } from "react";
import { motion } from "framer-motion";
import { Check, X } from "lucide-react";
import { cn } from "@/lib/cn";
import { useLens } from "@/lib/store";
import type { UnderstandingCheck as CheckType } from "@/lib/lens/contracts";

export function UnderstandingCheck({ check }: { check: CheckType }) {
  const answerUnderstandingCheck = useLens((s) => s.answerUnderstandingCheck);
  const [picked, setPicked] = useState<number | null>(null);
  const [busy, setBusy] = useState(false);

  async function pick(i: number) {
    if (picked !== null || busy) return;
    setBusy(true);
    setPicked(i);
    await answerUnderstandingCheck(i);
    setBusy(false);
  }

  const answered = picked !== null;
  const correct = answered && picked === check.correctIndex;

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      className="rounded-2xl border border-ink-800/15 bg-white/60 p-4 backdrop-blur"
    >
      <div className="mb-1 text-[10px] font-semibold uppercase tracking-[0.14em] text-signal-deep">
        Understanding check
      </div>
      <p className="mb-3 text-[14px] font-medium text-ink-100">{check.question}</p>

      <div className="flex flex-col gap-1.5">
        {check.options.map((opt, i) => {
          const isPicked = picked === i;
          const isAnswer = answered && i === check.correctIndex;
          return (
            <button
              key={i}
              disabled={answered}
              onClick={() => pick(i)}
              className={cn(
                "flex items-center justify-between rounded-xl border px-3 py-2 text-left text-[13px] transition",
                !answered &&
                  "border-ink-800/15 hover:border-signal/50 hover:bg-signal/5",
                isAnswer && "border-emerald-500/50 bg-emerald-500/10 text-emerald-900",
                isPicked &&
                  !isAnswer &&
                  "border-rose-400/50 bg-rose-500/10 text-rose-900",
                answered && !isPicked && !isAnswer && "opacity-50"
              )}
            >
              <span>{opt}</span>
              {isAnswer && <Check className="size-4 shrink-0" />}
              {isPicked && !isAnswer && <X className="size-4 shrink-0" />}
            </button>
          );
        })}
      </div>

      {answered && (
        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="mt-3 text-[12px] leading-relaxed text-ink-400"
        >
          {correct
            ? check.rationale
            : // A wrong answer gets the reasoning, not the fact — the next
              // reasoning pass re-asks a simpler version of this.
              "Not quite. Hold that thought — I'll come at it from a different angle."}
        </motion.p>
      )}
    </motion.div>
  );
}
